apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: wordpress
type: Opaque
data:
  mysql-root-password: YWRtaW4tcGFzcw==  # base64 encoded (admin-pass)
  mysql-user-password: d29yZHByZXNz     # base64 encoded (wordpress)
